export { crearDeck }  from './create-deck.js'
export { pedirCarta } from './pedir-carta.js'
export { turnoComputadora } from './turno-computadora'
export { valorCarta } from './valor-carta.js'
export {crearCartaHTML} from './crear-carta-html.js'
